---
title: "How should companies do accounting?"
author:
- affiliation: Utah State University
  name: Zachary Nelson
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
  html_document:
    df_print: paged
  word_document: default
biblio-style: apsr
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
keywords: Automation, Accounting, Technology, Human Labor
bibliography: ./master.bib
spacing: double
abstract: In this article, we look into the field of accounting to see how automation
  affects the lives of accountants. We will explore how technology has hurt the field
  of accounting, as well as how technology has advanced the profession and companies
  as a whole. We will use these arguments to build a background and then use their
  arguments to prove that neither is completely correct, meaning, there is a need
  for advanced technology and human labor in the field of accounting to be successful.
---


>  

# Introduction
  For decades now, people have been toying with the idea that robots and automation will take over our every day lives. From doing our jobs to ruling the world, many television series and movies have taken these views to extreme levels. In 2018, things aren't quite to the extreme levels we see in some movies, but technology has become an important part of our everyday lives. There has been a debate amongst scholars and politicians for years as to whether or not technology is doing more good than harm within the job market. Some argue "that rapid technological change has been destroying jobs faster than it is creating them." @rotman2013technology Others argue that "automation is often used to make human workers more efficient, not necessarily to replace them. Rising productivity means businesses can do the same work with fewer employees, but it can also enable the businesses to expand production with their existing workers, and even to enter new markets." @rotman2013technology The question then becomes, who is right? Is automation and technology here to benefit the workforce, or put people out of work? Many companies have fallen behind the technological movement while others have full on embraced it, potentially too much.
  
  By replacing the word economists for accountants the questions James Buchanon poses will be the topic of discussion for this debate. What are accountants and companies doing and what should they be doing? @Buchanan1979 The methodology in the field of accounting has become a question of debate for many years now and that will be the area of study for this paper. As James Buchanon said "Unless we can, for some reason, accept the ever-changing activities of economists as being always a part of the necessary evolution of the discipline through time, as being 'on the highway,' it is essential that we look occasionally at the map or model for scietific progress that each of us surely carries around, consciously or unconcisouly, in his head." @Buchanan1979 Now while we aren't talking about economics in this paper, switching the word economics to accounting we can see a very valueable lesson from his words. Unless we are able to adapt to the ever changing world, we won't be able to survive in the profession. In order to be successful in the accounting profession, I propose that companies and professionals need to find the right amount of balance between human labor and technology in order to survive in the ever changing world we find ourselves in.

## Subsection 1 ( Benefits of Technology )
  Throughout the past century, technology has continued to advance to the point where it has simply become a part of everyday life. This advancement in technology is and should be considered a good thing as medicine has improved, entertainment has improved and became cheaper, and the list can go on and on. While the science and the manufacturing of technology has given people a place to work, the effects technology has on the workforce has come under much debate. Some people argue that "technological progress is eliminating the need for many types of jobs and leaving the typical worker worse off than before." @rotman2013technology @brynjolfsson2012race These scholars like to use the area of farming and manufacturing as an example of how technology has decreased the amount of jobs available in these fields. Over the past century, as technology has advanced, many of the jobs in these fields have disappeared. "Computers have increasingly taken over such tasks as bookkeeping, clerical work, and repetitive production jobs in manufacturing--- all of which typically provided middle-class pay. At the same time, higher-paying jobs requring creativity and problem-solving skills, often aided by computers have proliferated. So have low-skill jobs: demand has increased for restuarant workers, janitors, home health aides, and others doing service work that is nearly impossible to automate." @rotman2013technology I would tend to agree with this second point. While middle class jobs are declining, higher paying and lower paying jobs are still being created at a good pace. I don't believe that technolgy is hurting fields as much as others would argue, simply that the workforce today is ever changing and adapting. 
  
  Adapting is vital to success in todays world. Technology and robots in many cases are doing repetitive menial tasks for humans, thereby making the workforce more efficient. In accounting, technology has helped us combine and analyze all of the accounting data within a company, helping to make the company more profitable. In the past, humans had to collect all of the hand written receipts, bills, payroll, and so on doing journal entries and adding things by hand to then produce financial statments and finally analyze how the company was doing. Now, accounting systems have combined these processes making them simpler and more efficient so that accountants and companies can focus more on what the numbers are telling us, rather than simply the numbers themselves. A process that took hundreds of hours a month before, now should take half the time. As was mentioned earlier, this allows companies to then expand their production and enter new markets thus creating jobs in other areas. @rotman2013technology So while technology may be infringing on certain jobs, it has created jobs in other areas. The key is to adapt to these changes.

## Subsection 2 (Human labor)
  While noting the fears of certain scholars that technology is taking all of jobs we used to do, I tend to think that human intelligence and decision making is still far superior and needed now more than ever. In @rotman2013technology, it talks about the super computer Watson and various other robots helping in the manufacturing world. It talks about how Watson has been able to help doctors process the data to help diagnose patients, but that "it is far from having the type of judgment and intuition a physician often needs." This is the key and is the reason why humans will still be necessary in higher paying jobs such as accounting. As mentioned before, bookkeeping has been largely benefited by technology, allowing accountants to focus on the higher level corporate decisions that they should be involved with. In this day and age, computers are there to help humans process and analyze data, but the decision making and judgement calls required in accounting and corporate business are best made by humans. "How valuable an asset in all walks of life is knowledge of people, of local conditions, and special circumstances. To know of and put to use a machine not fully employed, or someone's skill which could be better utilized, or to be aware of a surplus stock which can be drawn upon during an interruption of supplies, is socially quite as useful as the knowledge of better alternative techniques." @Hayek1945 Human knowledge and experience is so valuable and allows people to make proper decisions.

  Another point that we should make concerning humans advantage over technology is situational uncertainty. "The big challenge is uncertainty. In other words, people are still far better at dealing with changes in their environment and reacting to unexpected events." @rotman2013technology Humans still have the best capabilities to respond to stress and malfunction within a workplace enviroment and that is an advantage we should maintain over technology for years to come. 

  Probably even more important in this field though, is the thought of risk. Computers can be programmed to tell you the proper avenue to take based off a reward to risk measure. However, how many times have people made it big by playing it safe all the time. Most of the big investment gurus and entrepeneurs took a risky decision based off prior knowledge and a gut feeling that paid off. Other people and computers, would have called these people insane, yet years later we praise them for their knowledge. In concluding this topic I implore the words of F.A Hayek "the ultimate decisions must be left to the people who are familiar with these circumstances, who know directly of the relevant changes and of the resources immediately available to meet them." @Hayek1945

## Subsection 3
  The problem with today's society and especially with accounting is that "our technologies are racing ahead but many of our skills and organizations are lagging behind." @brynjolfsson2012race Many accountants and companies think that they can lean to one side of the scale and still achieve success. However, the key in today's world is to use balance to achieve effiency which then leads to growth."Technological progress, in particular, improvements in computer hardware, software, and networks--- has been so rapid and so surprising that many present-day organizations, institutions, policies, and mindsets are not keeping up." @brynjolfsson2012race 

  In my experience, the older generations are sometimes leery to accept the new age technologies. When they fail to adapt to these changes, most companies then let them go, or in the case that they own their own business, they simply can't compete with others that are more efficient and are put out of business. Leaning too much to the side of human skills has proven devastating to these individuals. However, leaning too far to the other side has its downfalls as well. In my job right now, I often times have to make calls to banks or companies that use the automation of phone calls. While this is very beneficial for companies to do, it often times leads to frustration. How many times have you sat on the phone trying to talk to the robot with frustration because it doesn't understand what you are saying? Then you spend over an hour waiting for someone to talk with to answer your question? Companies that fall into this category then lose customers or even employees who feel overworked. In a recent interview I was in, it was brought up that at his place of work, in his former department, that the company had cut back the number of employees answering phone calls in order to use these advances in technology. This has led to a frustration with customers who can't get answers to their questions and frustration amongst employees who feel they are overworked and has led to one of the lowest ratings in the city on Glassdoor about places to work. As evidence, we have already interviewed multiple people for the same position looking to leave this company. 
  
# Main Section
  Now we return to the methodology presented by James Buchanon at the first of this paper. The answer to "What should accountants and companies do?" should be clear to us at this point. In order for a company, or an accounting firm to succeed in today's world, they must fully embrace technology while keeping good people, in order to have success. Let's imagine someone running a race. In order for someone to run and win a race, they must be in great physical condition. However, I want to think about it basically by examining the body. Think of the legs, if one leg happens to be way longer than the other, this will cause a lot of stress on the body. While that person may be able to keep up for part of the race, eventually they will fall behind. In order to best compete, someone must have equal size legs or in other words balance. Each leg in this scenario represents human labor and technology. If one side is longer(heavily invested in) eventually you will fall behind the competition.

  The idea of balance is universal and expands way beyond the scope of just accounting. We see balance in the United States government, you hear motivational speakers talking about the need to have a good work life balance, and gymnasts must have balance in order to perform their routines. Those are just a few examples of many that exist in life. Without balance systems, life, sports, and many others would cease to function properly.  In a company information session I recently attended, one of the founders of the company was asked how they were able to enter a competitive market so recently and succeed whereas others have failed. His answer was exactly to the point we have been illustrating in this paper. The reason he felt his company has been able to succeed and grow at such a rapid pace is because of their commitment to provide advanced technology for their employees, but also their commitment to hire the right employees who can interact well with the customers to provide them the best customer service possible. But how should companies obtain this balance?
  
  In order for a company to obtain balance and allow them to grow and enter new markets, first and foremost, they have to hire the right people. I have had the experience of working in food service where you hire anyone and everyone who walks in the door because of the high turnover and the need for workers. It leads to finding some great workers and a lot of bad workers, which in any industry, can be devastating. Switching to the financial industry, it has been a very different process in hiring. Hiring workers who are responsible for running your store hundreds of miles away is very scary. They are handling the business, its reputation, and a lot of cash. You want to make sure that you hire the right people or you can be in trouble very quickly. For example, at my current job we have had examples of both. A few months in, I helped hire a human resources assistant for the company. She has came in and done a great job, taking a lot of the load off of mine and my bosses shoulders. However, a year prior to that, the prior owner hired a woman to run one of our offices. In a recent audit of the store, my boss found that she had embezzled over 30,000 dollars from him over the span of a year. While I wish I could have been a little stricter on hiring methods in food service, ensuring you have good reputable people in the financial industry is much more important. However, no matter what business you are in, you must hire good employees to ensure that the business is running properly and effieciently to provide the best service to the customers or market you serve.
  
  We cannot forget however, that in today's world, human labor is not enough to succeed. Fast food for example would not be fast if employees had to write down every order and pass the order to the cooks after the order is complete. Imagine back in the days when we had to give paper receipts and could only pay with cash or check. Technology has advanced so much over the past couple decades and it has allowed workers to become more effiecient for our benefit. While technology has taken away jobs in some areas, it has created jobs in others and has made the jobs of employees much easier. In order to keep up in today's world, you must adapt and be willing to use updated technology. In my current place of work, we are in the process of changing loan management software and getting new underwriting tools in order to better compete in the industry. As technology has advanced and more competition created, it has hurt the company. The decision to stay with what they knew and not adapt, has caused them to fall behind, and now, try to reboot the company. 
  
  The profession of accounting has been around for a long time and will continue to exist as companies need accountants to help manage their money. However, just as is the case with previous examples, companies need to hire the right people for the job and be willing to get the proper technology to best compete in the industry. In order to expand and grow a company, you must know how you are doing. Without accountants providing executives with financial statements, they won't know precisely how things are going. In order to get those reports, they must have good accountants and updated technology in order to get good reports and get them in a timely manner. If you stick with excel and paper, the reports will take forever to compile. If you hire the wrong accountant, various things could go wrong. This is why companies need to have both in order to suceed. 

# Summary and Conclusion
  In this paper we have talked about the methodology in the field of accounting. What should accountants do? Should they remain steadfast in the ways of the past, using shoeboxes to hold their receipts? Relying on excel and other basic spreadsheets to track and maintain their financials? Or should they delve head on into the future and buy all the latest technology, forgetting about all the accountants and things that worked in the past? The answer is neither. In order to succeed in today's world, accountants must find balance between human labor and technology. While technology may be advancing, humans still maintain certain advantages and are much more equiped to interact with other humans. When balance is achieved, power and stability are created, and accountants and their employers can begin to thrive in a competitive world. As Euripededs once said, "The best and safest thing is to keep a balance in your life, acknowledge the great powers around us and in us. If you can do that, and live that way, you are really a wise man."


<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

